server:
  port: 8081

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  application:
    name: oris_spring
  datasource:
    url: jdbc:postgresql://localhost:5432/oris_spring
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      pool-name: OrisHikariPool